apiVersion: v1

kind: Service 

metadata:
  name: doctor-service
  labels:
    app: doctor-service-svc-label

spec:
  ports:
  - port: 8888
    name: http

  selector:
    app: doctor-service-v1-v2

  type: NodePort

---

apiVersion: apps/v1

kind: Deployment

metadata:
  name: doctor-service-deployment-v1
  labels:
    app: doctor-service-dep-label

spec:
  replicas: 1
  selector: 
    matchLabels: 
      app: doctor-service-v1-v2

  template: # template for the pods
    metadata:
      labels:
        app: doctor-service-v1-v2
        version: v1

    spec:
      containers:
      - name: vets-service-ver1
        image: gcr.io/app-mod-gebu-trainees/online-appointment-doctor-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8899
